### ISSUE TITLE
Destroying sddc_group times out and then fails on subsequent attempts

### ISSUE THREAD

**Issue by jordanaroth** [vmware/terraform-provider-vmc#169]
### Describe the bug

Destroying the sddc_group times out and then fails on subsequent attempts. 

The first run times out with:

```
vmc_sddc_group.sddc_group: Still destroying... [id=[removed], 29m51s elapsed]
╷
│ Error: expected task type: UPDATE_MEMBERS to be finished PENDING
```

On subsequent runs it outputs a bug report:

```
vmc_sddc_group.sddc_group: Refreshing state... [id=[removed]]
╷
│
│   with vmc_sddc_group.sddc_group,
│   on main.tf line 52, in resource "vmc_sddc_group" "sddc_group":
│   52: resource "vmc_sddc_group" "sddc_group" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-vmc_v1.12.0.exe plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 178 [running]:
github.com/vmware/terraform-provider-vmc/vmc.resourceSddcGroupRead({0x19ae320?, 0xc000303530?}, 0xc000604180, {0x1807860?, 0xc00017f400?})
        github.com/vmware/terraform-provider-vmc/vmc/resource_vmc_sddc_group.go:234 +0xca5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000168fc0, {0x19ae320, 0xc000303530}, 0xd?, {0x1807860, 0xc00017f400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:359 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000168fc0, {0x19ae320, 0xc000303530}, 0xc000317ba0, {0x1807860, 0xc00017f400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:650 +0x47b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000009008, {0x19ae278?, 0xc0001fd400?}, 0xc0001fd480)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/grpc_provider.go:613 +0x488
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00024a280, {0x19ae320?, 0xc000302c00?}, 0xc000140f00)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:746 +0x43d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1825000?, 0xc00024a280}, {0x19ae320, 0xc000302c00}, 0xc000140ea0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027e380, {0x19b1e18, 0xc000067380}, 0xc00000c480, 0xc0002b4450, 0x1ed3570, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00027e380, {0x19b1e18, 0xc000067380}, 0xc00000c480, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-vmc_v1.12.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Reproduction steps

1. Build a terraform plan that includes an sddc group example:
```
resource "vmc_sddc_group" "sddc_group" {
   name  = var.sddc_group_name
   description    = var.sddc_group_description
   sddc_member_ids = [vmc_sddc.sddc_a.id, vmc_sddc.sddc_b.id]
}
```
2. Apply the terraform plan to create the sddcs and sddc group
3. Run 'terraform destroy'

### Expected behavior

Terraform should remove the sddc group and sddcs

**Comment by dimitarproynov** [comment]
I've incresed timeouts for SDDC Group operations and added additional checks for resiliency so the go panic doesn't happen. Fix will be out in next release.
